name: Publish Library

on:
  workflow_call:
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: Charmhub upload orc8r-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Publish NRF lib
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          set -eux
          echo "Publishing lib"
          charmcraft publish-lib charms.sdcore_nrf.v0.fiveg_nrf
